//HintName: Test.TestClass_T1_T2_Sink.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0618 // Suppress obsolete

namespace Test
{
    partial class TestClass<T1, T2> : global::Darp.Utils.Messaging.IMessageSinkProvider
    {
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Utils.Messaging.Generator", "GeneratorVersion")]
        [global::System.Obsolete("This field is not intended to be used in use code. Use 'GetMessageSink'")]
        private ___MessageSink? ___lazyMessageSink;

        /// <inheritdoc />
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Utils.Messaging.Generator", "GeneratorVersion")]
        public global::Darp.Utils.Messaging.IMessageSink GetMessageSink()
        {
            return ___lazyMessageSink ??= new ___MessageSink(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Darp.Utils.Messaging.Generator", "GeneratorVersion")]
        private sealed class ___MessageSink
            : global::Darp.Utils.Messaging.IMessageSink<T1>
        {
            private readonly TestClass<T1, T2> _parent;

            public ___MessageSink(TestClass<T1, T2> parent)
            {
                _parent = parent;
            }

            public void Publish(in T1 message)
            {
                _parent.OnT(message);
            }
        }
    }
}
