namespace Darp.Utils.Messaging.Generator;

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using Microsoft.CodeAnalysis;
using static RoslynHelper;

internal static class SourceEmitter
{
    public static bool TryEmit(
        SourceTypeInfo sourceInfo,
        [NotNullWhen(true)] out string? code,
        out List<Diagnostic> diagnostics
    )
    {
        using var stringWriter = new StringWriter();
        using var writer = new IndentedTextWriter(stringWriter);
        diagnostics = [];

        writer.WriteMultiLine(
            """
            // <auto-generated/>
            #nullable enable
            #pragma warning disable CS0618 // Suppress obsolete
            """
        );
        writer.WriteLine();
        EmitOptionalNamespaceStart(writer, sourceInfo.Symbol);

        var typeName = sourceInfo.Symbol.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
        var publishModifier = sourceInfo.Symbol.IsSealed ? "private" : "protected";
        var lockType = sourceInfo.IsCompiledWithNet9OrGreater ? "global::System.Threading.Lock" : "object";
        var refStructConstraint = sourceInfo.IsCompiledWithNet9OrGreater ? " where T : allows ref struct" : "";
        writer.WriteMultiLine(
            $$"""
            partial class {{typeName}} : global::Darp.Utils.Messaging.IMessageSource
            {
                [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                {{GetGeneratedVersionAttribute()}}
                [global::System.Obsolete("This field is not intended to be used in use code")]
                private global::System.Collections.Immutable.ImmutableArray<global::Darp.Utils.Messaging.IMessageSink> ___messageSinks =
                    global::System.Collections.Immutable.ImmutableArray<global::Darp.Utils.Messaging.IMessageSink>.Empty;

                /// <summary> Publish a new message </summary>
                /// <param name="message"> The message to be published </param>
                /// <typeparam name="T"> The type of the message to be published </typeparam>
                {{GetGeneratedVersionAttribute()}}
                {{publishModifier}} void PublishMessage<T>(in T message){{refStructConstraint}}
                {
                    foreach (global::Darp.Utils.Messaging.IMessageSink eventReceiver in ___messageSinks)
                    {
                        if (eventReceiver is global::Darp.Utils.Messaging.IMessageSink<T> receiver)
                            receiver.Publish(message);
                        else if (eventReceiver is global::Darp.Utils.Messaging.IAnyMessageSink anyReceiver)
                            anyReceiver.Publish(message);
                    }
                }

                /// <inheritdoc />
                {{GetGeneratedVersionAttribute()}}
                public global::System.IDisposable Subscribe(global::Darp.Utils.Messaging.IMessageSink sink)
                {
                    ___messageSinks = ___messageSinks.Add(sink);
                    return global::Darp.Utils.Messaging.FuncDisposable.Create(
                        (Self: this, Sink: sink),
                        state =>
                        {
                            state.Self.___messageSinks = state.Self.___messageSinks.Remove(state.Sink);
                        }
                    );
                }
            }
            """
        );

        EmitOptionalNamespaceEnd(writer, sourceInfo.Symbol);

        code = stringWriter.ToString();
        return true;
    }
}
